### ISSUE TITLE
Add support for badgeColor(int) 

### ISSUE THREAD

**Issue by muigukenneth** [minibugdev/DrawableBadge#15]
Nice Library, 
but can you please add support for passing color as int since i wanna update color dynamically. 
Thanks.

**Comment by minibugdev** [comment]
Thanks @muigukenneth, 

This library already support to set `badgeColor` with `int`([@ColorRes](https://developer.android.com/reference/android/support/annotation/ColorRes.html)).
Or, you need to set badge color by programmatically. Something like generated color ?

**Comment by muigukenneth** [comment]
@minibugdev i want to use color not from resource please.

**Comment by minibugdev** [comment]
I see, can you give me a sample code.
I'm not sure what `int` did you mean?

**Comment by muigukenneth** [comment]
Please add another method like fun `badgeColor(badgeColorRes: Int) = apply { this.badgeColor =  badgeColorRes }`

i just removed "@ColorRes" and "ContextCompat.getColor(context, badgeColorRes)" to enable using color as an Integer.
