### ISSUE TITLE
Add support for Badge Position CENTER

### ISSUE THREAD

**Issue by priyanshu2112** [minibugdev/DrawableBadge#16]
Library is very useful,  and all the provided methods are amazing.
but the only feature which lacks is the center positioning of badge over parent Drawable.

**Comment by minibugdev** [comment]
Thanks @priyanshu2112,

We'll support more position `CENTER_LEFT`  `CENTER_RIGHT`  `CENTER_TOP`  `CENTER_BOTTOM` on next release.
