### ISSUE TITLE
Imageview Tint overrides badge colors

### ISSUE THREAD

**Issue by Mithrandir21** [minibugdev/DrawableBadge#17]
If the badge added to an Imageview that has ```android:tint=...``` in the layout, the tint color overrides any colors added in the builder.

Example:
```
<ImageView
        android:id="@+id/icon"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:tint="@android:color/white"/>
```

The badge (number and background) will all be white here, regardless of what colors are chosen in the DrawableBadge builder.

**Comment by minibugdev** [comment]
Thanks for report @Mithrandir21,

We'll work on it and try to fix it ASAP :)

**Comment by hayribakici** [comment]
Hey!
Again, thank you for this super simple-to-use library. 
I also came across the same problem. After we tint the drawable (in our case we set 
`imageView.colorFilter`, the badge becomes the same color as the colorFilter. Any news on this?

thank you

**Comment by minibugdev** [comment]
Hi @Mithrandir21 @hayribakici 

We couldn't fix this issue cause of this library working by get `drawable` source and draw `badge` on top it and result of library is still drawable.

For `android:tint` and `ImageView.colorFilter` are functions of `ImageView` which use drawable result from library and `ImageView` apply tint after render drawable in code below

**ImageView.java line 1016-1017**
``` java
private void updateDrawable(Drawable d) {
    if (d != mRecycleableBitmapDrawable && mRecycleableBitmapDrawable != null) {
        mRecycleableBitmapDrawable.setBitmap(null);
    }

    boolean sameDrawable = false;

    if (mDrawable != null) {
        sameDrawable = mDrawable == d;
        mDrawable.setCallback(null);
        unscheduleDrawable(mDrawable);
        if (!sCompatDrawableVisibilityDispatch && !sameDrawable && isAttachedToWindow()) {
            mDrawable.setVisible(false, false);
        }
    }

    mDrawable = d;

    if (d != null) {
        d.setCallback(this);
        d.setLayoutDirection(getLayoutDirection());
        if (d.isStateful()) {
            d.setState(getDrawableState());
        }
        if (!sameDrawable || sCompatDrawableVisibilityDispatch) {
            final boolean visible = sCompatDrawableVisibilityDispatch
                    ? getVisibility() == VISIBLE
                    : isAttachedToWindow() && getWindowVisibility() == VISIBLE && isShown();
            d.setVisible(visible, true);
        }
        d.setLevel(mLevel);
        mDrawableWidth = d.getIntrinsicWidth();
        mDrawableHeight = d.getIntrinsicHeight();
        applyImageTint();
        applyColorMod();

        configureBounds();
    } else {
        mDrawableWidth = mDrawableHeight = -1;
    }
}
```
