### ISSUE TITLE
feature request : Support text or drawable in badge

### ISSUE THREAD

**Issue by MarineDr** [minibugdev/DrawableBadge#26]
i just want to custom my badge : remove numbers and show "•••" for example, thanks !

**Comment by minibugdev** [comment]
Okay, may be on weekend I gonna catch it :)

**Comment by minibugdev** [comment]
Hi @MarineDr, 

I already publish version `2.0.1` to support to set show counter feature.

**Comment by MarineDr** [comment]
thanks for your work, but i wanted to write some custom strings instead of number in the badge. I just updated your work by myself and quote your github repository so it's okay for me thanks !
